Lambda-School-Labs/bg-emotion-tracker-be

src/main/java/com/lambdaschool/oktafoundation/models/Member.java
And extends Auditable for Member class/table
=> Adds Member getters, setters, and constructors

src/main/java/com/lambdaschool/oktafoundation/SeedData.java, src/main/java/com/lambdaschool/oktafoundation/controllers/ClubActivityController.java, src/main/java/com/lambdaschool/oktafoundation/controllers/ClubController.java, src/main/java/com/lambdaschool/oktafoundation/controllers/ClubUsersController.java, src/main/java/com/lambdaschool/oktafoundation/controllers/UserController.java, src/main/java/com/lambdaschool/oktafoundation/repository/ClubActivityRepository.java, src/main/java/com/lambdaschool/oktafoundation/repository/ClubRepository.java, src/main/java/com/lambdaschool/oktafoundation/repository/ClubUsersRepository.java, src/main/java/com/lambdaschool/oktafoundation/services/ClubActivityService.java, src/main/java/com/lambdaschool/oktafoundation/services/ClubActivityServiceImpl.java, src/main/java/com/lambdaschool/oktafoundation/services/ClubService.java, src/main/java/com/lambdaschool/oktafoundation/services/ClubServiceImpl.java, src/main/java/com/lambdaschool/oktafoundation/services/ClubUsersService.java, src/main/java/com/lambdaschool/oktafoundation/services/ClubUsersServiceImpl.java
Created Endpoints for Admin, documentation and notes still need to be added on some of the files.
=> Adminserviceendpoints

src/main/java/com/lambdaschool/oktafoundation/SeedData.java
[Trello 'To Do' seed data task](https://trello.com/c/slmUTswT/23-create-usable-and-robust-seed-data-for-testing)
Seed Data updated to give us usable data. These should be compatible with authorization with Okta. 
Roles are as follows
admin:
llama001@maildrop.cc
Test001Test
YDP:
username: llama002@maildrop.cc
password: Test002Test
CD:
llama003@maildrop.cc
Test003Test
KID:
llama004@maildrop.cc
Test004Test
llama005@maildrop.cc
Test005Test
llama006@maildrop.cc
Test006Test
llama007@maildrop.cc
Test007Test
llama008@maildrop.cc
Test008Test
=> Feature/update seed data/chase bianchi

src/main/java/com/lambdaschool/oktafoundation/models/Activity.java, src/main/java/com/lambdaschool/oktafoundation/models/ClubActivities.java, src/main/resources/application.properties, target/classes/application.properties
I had a few duplicate lines of code from last merge conflict. Easy fix, just deleted the duplicate lines.
=> fix merge conflict bugs

src/main/java/com/lambdaschool/oktafoundation/controllers/ActivityController.java, src/main/java/com/lambdaschool/oktafoundation/repository/ActivityRepository.java, src/main/java/com/lambdaschool/oktafoundation/services/ActivityService.java, src/main/java/com/lambdaschool/oktafoundation/services/ActivityServiceImpl.java
POST /activities/activity/addclub/{clubid}
with body of activity
{
"activityname":test,
"activityid":5
}
If no activityID provided, a new activity is created if activity name is not found
( which means you never HAVE to provide an activityID aside from the potential slight speed advantage from using ID to query the DB instead of search by name)
=> tentatively adding posting club-activity

FrequentlyUsedEndpoints.md
Adding a "practical documentation" for reference, this should be a list of important endpoints for the frontend to actually use, unimportant endpoints should not be documented here.
=> Initial practical endpoint documentation

src/main/java/com/lambdaschool/oktafoundation/config/OktaAuthSecurityConfig.java
=> fix missing auth in config

src/main/java/com/lambdaschool/oktafoundation/SeedData.java, src/main/java/com/lambdaschool/oktafoundation/controllers/ActivityController.java, src/main/java/com/lambdaschool/oktafoundation/controllers/ClubController.java, src/main/java/com/lambdaschool/oktafoundation/models/ClubUsers.java, src/main/java/com/lambdaschool/oktafoundation/models/ClubUsersId.java, src/main/java/com/lambdaschool/oktafoundation/models/User.java, src/main/java/com/lambdaschool/oktafoundation/repository/ClubUsersRepository.java, src/main/java/com/lambdaschool/oktafoundation/services/ClubServiceImpl.java
Now user contains a list of clubs the user belong (though I assume it would be only one typically)
Club contains a list of users (staff, not member as in kids)
Seed data now have Anderson with 3 users and Caitlin with 1 user.
=> fixing clubUser relationships, added users to clubs in seeddata

pom.xml, src/main/java/com/lambdaschool/oktafoundation/OktaFoundationApplication.java, src/main/java/com/lambdaschool/oktafoundation/SeedData.java, src/main/java/com/lambdaschool/oktafoundation/controllers/ClubController.java
This patch includes
1. YDP should now be able to get club's details by clubid.
2. pom.xml modified to allow main branch to be heroku-deployable
3. Added 'Club Checkout' activity for all clubs in seed.
=> YDP auth fix; config changes; new seed data for 'Club Checkout'

src/main/java/com/lambdaschool/oktafoundation/controllers/ReportController.java, src/main/java/com/lambdaschool/oktafoundation/views/ClubActivityReactionCounts.java, src/main/java/com/lambdaschool/oktafoundation/views/MemberReactionCounts.java
- Per request of @pak11273 , report by counts endpoints added to make pie charts on the frontend.
- Two new view models for report by counts
- Minor refactors in ReportController
- Endpoint documentation at <a href="https://github.com/Lambda-School-Labs/bg-emotion-tracker-be-b/blob/main/FrequentlyUsedEndpoints.md#get-counts-of-feedbacks-member-given-to-activities"> HERE </a>
---
=> Added report by counts

README.md
A rewrote of the readme file to be more informative
Preview:
https://github.com/Lambda-School-Labs/bg-emotion-tracker-be-b/tree/format/README
=> reworked README

pom.xml, src/test/resources/application.properties, target/classes/application.properties, target/test-classes/application.properties
This PR is meant to change the name of the Java back so we can deploy our own version.
Also removed some application.properties that should not have been there.
=> Changes project name for LABS 35 deployment

src/main/java/com/lambdaschool/oktafoundation/SeedData.java, src/main/java/com/lambdaschool/oktafoundation/models/MemberReactions.java, src/main/java/com/lambdaschool/oktafoundation/models/Reaction.java, src/main/java/com/lambdaschool/oktafoundation/services/ReactionServiceImpl.java
Description
Creates a field for tracking negative member reaction responses. Creates field for assigning an Integer value to a reaction.
Why was this work done?  
We needed a better way to store the value information for the member reactions. These values are going to be used for analysis to display data visualizations in the dashboard.
We also are going to work on a alerts feature so we added a field for keeping track if those alerts have been handled or not.
Change Status  
[x] Completed, ready to review and merge  
Has This Been Tested  
[x] Yes
Checklist
[x] My code follows the style guidelines of this project  
[x] I have performed a self-review of my own code  
[x] My code has been reviewed by at least one peer  
[x] I …
=> Creates a field for tracking negative member reaction responses. Creates field for assigning an Integer value to a reaction.

src/main/java/com/lambdaschool/oktafoundation/SeedData.java, src/main/java/com/lambdaschool/oktafoundation/views/LeaderBoardData.java, src/main/java/com/lambdaschool/oktafoundation/views/LeaderboardReactions.java
Description
Added the rest of the of the clubs to be included when generating random reactions.
Why was this work done?  
We only had 5 clubs of the 9 clubs we know about in the data set. We of course want all of them.
Please delete options that are not relevant.  
Change Status  
[x] Completed, ready to review and merge  
Checklist
[x] My code follows the style guidelines of this project  
[x] I have performed a self-review of my own code  
[] My code has been reviewed by at least one peer  
[x] I have commented my code, particularly in hard-to-understand areas  
[] I have made corresponding changes to the documentation  
[x] My changes generate no new warnings  
=> Adds the rest of the clubs to the data set.

src/main/java/com/lambdaschool/oktafoundation/config/OktaAuthSecurityConfig.java, src/main/java/com/lambdaschool/oktafoundation/controllers/MemberReactionsController.java, src/main/java/com/lambdaschool/oktafoundation/repository/MemberReactionRepository.java
Description
Added an Alert endpoint for getting all Member Reactions where Reactionresolved = false
What work was done?
Added a query into MemberReactionsRepository, created the endpoint in MemberReactionsController, and also Created the endpoint in OktaAuthSecurityConfig with permissions to the roles of: Admin, CD, and YDP
This endpoint gives the data required for a major feature being worked on in the front end.
Change Status
Checklist
[x] I have commented my code, particularly in hard-to-understand areas …
=> endpoint for alerts created, query created in memberreationrepository

src/main/java/com/lambdaschool/oktafoundation/controllers/MemberReactionsController.java, src/main/java/com/lambdaschool/oktafoundation/repository/MemberReactionRepository.java
Description
Added checkout to the alert endpoint
What work was done?
Added "or activityid=14" to alert query
This endpoint gives the data required for a major feature being worked on in the front end.
Change Status
Checklist
[x] I have commented my code, particularly in hard-to-understand areas
=> fixed alert endpoint to for checkin AND checkout

src/main/java/com/lambdaschool/oktafoundation/models/Club.java
Changed code to not change clubname to lowercase only
=> removed toLowercase

src/main/java/com/lambdaschool/oktafoundation/config/OktaAuthSecurityConfig.java, src/main/java/com/lambdaschool/oktafoundation/controllers/LeaderboardController.java, src/main/java/com/lambdaschool/oktafoundation/repository/ActivityRepository.java, src/main/java/com/lambdaschool/oktafoundation/repository/ClubRepository.java, src/main/java/com/lambdaschool/oktafoundation/repository/MemberReactionRepository.java, src/main/java/com/lambdaschool/oktafoundation/services/ActivityServiceImpl.java, src/main/java/com/lambdaschool/oktafoundation/services/ClubService.java, src/main/java/com/lambdaschool/oktafoundation/services/ClubServiceImpl.java, src/main/java/com/lambdaschool/oktafoundation/services/ReactionService.java, src/main/java/com/lambdaschool/oktafoundation/services/ReactionServiceImpl.java
Description
The leaderboard endpoint needed cleaning up. We also needed to allow access to the endpoint to the correct authenticated users.
What work was done?  
Created service methods that called their respective repositories. Previously the controller was calling the repositories directly, but now they call the services. Also added rules to allow the /leaderboard/leaderboard to be accessed by authenticated Club director and Admin accounts.
Why was this work done?  
To allow access to the frontend to fetch the data needed.
[x] Completed, ready to review and merge  
Checklist
[x] My code follows the style guidelines of this project  
[x] I have performed a self-review of my own code  
[] My code has been reviewed by at least one peer  
[] I have commented my code, particularly in …
=> Cleans up leaderboard endpoint and allows permission to access to admin and cd.

src/main/java/com/lambdaschool/oktafoundation/controllers/MemberReactionsController.java, src/main/java/com/lambdaschool/oktafoundation/repository/MemberReactionRepository.java, src/main/java/com/lambdaschool/oktafoundation/services/MemberReactionService.java, src/main/java/com/lambdaschool/oktafoundation/services/MemberReactionServiceImpl.java, src/main/java/com/lambdaschool/oktafoundation/views/AlertData.java
Description
Changed the shape of data returned from the alert endpoint
What work was done?
created a view for alertdata, changed memberreactiorepos query, implemented view in memberreaction service/serviceimpl/controller.
To simplify the data pushed to the frontend, and to trim out data that is not needed in the get request
Checklist
=> Changed data shape for alert endpoint

src/main/java/com/lambdaschool/oktafoundation/config/OktaAuthSecurityConfig.java, src/main/java/com/lambdaschool/oktafoundation/controllers/MemberReactionsController.java, src/main/java/com/lambdaschool/oktafoundation/models/MemberReactions.java, src/main/java/com/lambdaschool/oktafoundation/services/MemberReactionService.java, src/main/java/com/lambdaschool/oktafoundation/services/MemberReactionServiceImpl.java, src/main/java/com/lambdaschool/oktafoundation/views/AlertData.java
Description
Created endpoint to change reactionresolved value to True
This endpoint needed to be created so the frontend can use the data to display on the dashboard in alerts
Change Status
Checklist
=> added put endpoint to flip boolean reactionresolved to true

src/main/java/com/lambdaschool/oktafoundation/config/OktaAuthSecurityConfig.java, src/main/java/com/lambdaschool/oktafoundation/controllers/MemberReactionsController.java, src/main/java/com/lambdaschool/oktafoundation/models/MemberReactions.java, src/main/java/com/lambdaschool/oktafoundation/services/MemberReactionService.java, src/main/java/com/lambdaschool/oktafoundation/services/MemberReactionServiceImpl.java, src/main/java/com/lambdaschool/oktafoundation/views/AlertData.java
Reverts Lambda-School-Labs/bg-emotion-tracker-be#56
=> Revert "added put endpoint to flip boolean reactionresolved to true"

src/main/java/com/lambdaschool/oktafoundation/controllers/MemberReactionsController.java, src/main/java/com/lambdaschool/oktafoundation/repository/MemberReactionRepository.java, src/main/java/com/lambdaschool/oktafoundation/views/AlertData.java
Description
Created endpoint to change reactionresolved value to True
This endpoint needed to be created so the frontend can use the data to display on the dashboard in alerts
Change Status
Checklist
=> Tweaked data structure and also put request json

src/main/java/com/lambdaschool/oktafoundation/services/MemberReactionService.java, src/main/java/com/lambdaschool/oktafoundation/services/MemberReactionServiceImpl.java
Description
Added in the services for the put(update) request
This endpoint needed to be created so the frontend can use the data to display on the dashboard in alerts
Change Status
Checklist
=> here are the services sorry :)

src/main/java/com/lambdaschool/oktafoundation/models/MemberReactions.java
Description
Created endpoint to change reactionresolved value to True
This endpoint needed to be created so the frontend can use the data to display on the dashboard in alerts
Change Status
Checklist
=> added model changes

src/main/java/com/lambdaschool/oktafoundation/controllers/MemberController.java, src/main/java/com/lambdaschool/oktafoundation/models/Member.java, src/main/java/com/lambdaschool/oktafoundation/services/MemberService.java, src/main/java/com/lambdaschool/oktafoundation/services/MemberServiceImpl.java
Added active value to member module
Implemented member update to toggle member active feature
Created controller for updating member active feature
No commented out unused code
=> added active feature to member

src/main/java/com/lambdaschool/oktafoundation/SeedData.java
Changed values of reactions from 1-5 to 1-10
=> Assigned 1-10 reactionValues

src/main/java/com/lambdaschool/oktafoundation/SeedData.java, src/main/java/com/lambdaschool/oktafoundation/controllers/MemberController.java
Fixed wrong spell of club Catlin
Added authorization check for members update controller, to be accessed only by Admin or Club director
=> fixed spell check

src/main/java/com/lambdaschool/oktafoundation/models/CheckInOutReaction.java, src/main/java/com/lambdaschool/oktafoundation/services/MemberServiceImpl.java
Added sort method by member_table_id to MemberServiceImpl file
=> Added sort method to MemberServiceImpl

src/main/java/com/lambdaschool/oktafoundation/SeedData.java, src/main/java/com/lambdaschool/oktafoundation/controllers/ClubActivityController.java, src/main/java/com/lambdaschool/oktafoundation/models/Reaction.java, src/main/java/com/lambdaschool/oktafoundation/services/ReactionServiceImpl.java, src/main/java/com/lambdaschool/oktafoundation/views/ActivityReaction.java
Changed values for emojis in Seed Data to be from 0.5 to 5. For that also changed reactionint type from int to double. Made changes to all files where reactionint type was used.
=> changed emojis to double value and reactionint type

src/main/java/com/lambdaschool/oktafoundation/SeedData.java, src/main/java/com/lambdaschool/oktafoundation/models/MemberReactions.java
Changed resolved to be true for reactions with value more that 3. Changed order of reactions in Seed Data.
=> negative reactions with value less than 3
